image:
  file: .gitpod.Dockerfile
tasks:
  - name: MySQL database
    before: init_mysql.sh
  - name: Node.js server
    before: npm ci
    init: node app.js
    command: node app.js
vscode:
  extensions:
    - dbaeumer.vscode-eslint
ports:
  - port: 1700
    onOpen: open-browser
