image:
  file: .gitpod.Dockerfile
tasks:
  - name: Startup script
    command: sh ./startup.sh
  - name: MySQL
    init: sh ./init_mysql.sh
  - name: Node.js
    init: npm ci
vscode:
  extensions:
    - dbaeumer.vscode-eslint
ports:
  - port: 1700
    onOpen: open-browser
  - port: 33060
    onOpen: ignore
  - port: 3306
    onOpen: ignore
