image:
  file: .gitpod.Dockerfile
tasks:
  - name: MySQL database
    init: sh ./init_mysql.sh
    command: sh ./start_mysql.sh
  - name: Node.js server
    init: npm ci
    command: node app.js
vscode:
  extensions:
    - dbaeumer.vscode-eslint
ports:
  - port: 1700
    onOpen: open-browser
  - port: 33060
    onOpen: ignore
  - port: 3306
    onOpen: ignore
