image:
  file: .gitpod.Dockerfile
tasks:
  - name: Node.js server
    before: npm ci
    init: node app.js
    command: node app.js
  - name: MySQL database
    before: start_mysql.sh
    init: init_mysql.sh
vscode:
  extensions:
    - dbaeumer.vscode-eslint
ports:
  - port: 1700
    onOpen: open-browser
